@startuml IATI Message Queue Service and Connected Apps
scale 2000*1600

skinparam noteFontSize 10

!include <azure/AzureCommon>
!include <azure/Compute/AzureFunction>
!include <azure/Containers/AzureContainerInstance>
!include <azure/Integration/AzureServiceBus>
!include <azure/Databases/AzureDatabaseForPostgreSQL>
!include <azure/Storage/AzureBlobStorage>


AzureServiceBus(IATIMessageQueueService, "\nIATI Message Queue Service", "iati-mq-INSTANCE")

AzureContainerInstance(BulkDataService, "\nBulk Data Service\n(Data Getter)", "bulk-data-service-INSTANCE")

AzureFunction(DataDownloader, "\nData Downloader", "")

AzureBlobStorage(IATIXMLCache, "\nIATI XML Cache", "bulk-data.iatistadnard.org")

AzureDatabaseForPostgreSQL(BDSPersistentStorage, "Bulk Data Service Persistent Data Storage", "")

component SuiteCRM

component Dashboard

note right of SuiteCRM
Connections from an app to the Message Queue Service begin with either **publish:** or **consume:**. The edge description lists the action type and the <<""topic"">> or <<""subscription"">> name (without the instance postfix).
end note


SuiteCRM -down-> IATIMessageQueueService : **publish**:\n<<""iati-mq-registry-changes-topic"">>\nDATASET_CREATED,\nDATASET_UPDATED,\nDATASET_DELETED,\n\nREPORTING_ORG_CREATED,\nREPORTING_ORG_UPDATED,\nREPORTING_ORG_DELETED

Dashboard -left--( IATIMessageQueueService : **consume**:\n<<""iati-mq-registry-changes-sub-dashboard"">>\nDATASET_CREATED,\nDATASET_UPDATED,\nDATASET_DELETED,\n\nREPORTING_ORG_CREATED,\nREPORTING_ORG_UPDATED,\nREPORTING_ORG_DELETED

Dashboard -left-( IATIMessageQueueService : **consume**:\n<<""iati-mq-download-results-sub-dashboard"">>\nDOWNLOAD_ATTEMPT_RESULT

BulkDataService -up--> IATIMessageQueueService : **publish**:\n<<""iati-mq-downloader-queue"">>\n<<""iati-mq-downloader-high-priority-queue"">>\nDOWNLOAD_REQUIRED

BulkDataService --( IATIMessageQueueService : **consume**:\n<<""iati-mq-registry-changes-sub-data-getter"">>\nDATASET_CREATED,\nDATASET_UPDATED,\nDATASET_DELETED,\n\nREPORTING_ORG_CREATED,\nREPORTING_ORG_UPDATED,\nREPORTING_ORG_DELETED

BulkDataService -up-( IATIMessageQueueService : **consume**:\n<<""iati-mq-download-results-sub-data-getter"">>\nDOWNLOAD_ATTEMPT_RESULT

BulkDataService --> IATIXMLCache : upload bulk ZIP

BulkDataService <--> BDSPersistentStorage : save state

DataDownloader -right-( IATIMessageQueueService : **consume**:\n<<""iati-mq-downloader-queue"">>\n<<""iati-mq-downloader-high-priority-queue"">>\nDOWNLOAD_REQUIRED

DataDownloader -right-> IATIMessageQueueService : **publish**:\n<<""iati-mq-download-results-topic"">>\nDOWNLOAD_ATTEMPT_RESULT

DataDownloader -down-> IATIXMLCache : upload individual\nIATI datasets\n(XML and ZIP)

@enduml
