@startuml IATI Message Queue Service and Connected Apps
scale 2000*1600

package Messages {
artifact DatasetStaleMessage
note bottom
    { 
      id: dataset-id
    }
end note

artifact ReportingOrgUpdatedMessage
note bottom
    { 
      id: reporting-org-id,
      updated-fields: [field1, field2, ...]
    }
end note

artifact DatasetUpdatedMessage
note bottom
    { 
      id: dataset-id,
      updated-fields: [field1, field2, ...]
    }
end note
}


component IATIMessageQueueService

component DataGetter

component SuiteCRM

component Dashboard

SuiteCRM -down-> IATIMessageQueueService : publish:\n DatasetUpdatedMessage


SuiteCRM -down-> IATIMessageQueueService : publish:\n ReportingOrgUpdatedMessage


DataGetter -up-> IATIMessageQueueService : push: \n DatasetStaleMessage

DataGetter -( IATIMessageQueueService : consume: \n DatasetUpdatedMessage

DataGetter -( IATIMessageQueueService : consume: \n DatasetStaleMessage


Dashboard -up-( IATIMessageQueueService : consume: \n DatasetUpdatedMessage

Dashboard -up-( IATIMessageQueueService : consume: \n ReportingOrgUpdatedMessage

@enduml
