---
name: Run CI tasks

on: [pull_request]

jobs:
  build:
    name: YAML Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML files
        run: "yamllint ."
