---
name: Autogenerate documentation

on:
  workflow_dispatch:
  push:
    branches: [develop]
    paths: [specification/**]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Generating HTML for SuiteCRM
        uses: asyncapi/cli@v3.2.0
        with:
          template: "@asyncapi/html-template@3.0.0"  # As its a template from npm with a @ it must be in quotes
          parameters: --use-new-generator --force-write
          filepath: specification/iati-mq-suitecrm.yaml
          output: docs/specification-mq-suitecrm

      - name: Generating HTML for Registry record update clients
        uses: asyncapi/cli@v3.2.0
        with:
          template: "@asyncapi/html-template@3.0.0"  # As its a template from npm with a @ it must be in quotes
          parameters: --use-new-generator --force-write
          filepath: specification/iati-mq-clients.yaml
          output: docs/specification-mq-clients

      - name: Commit and push documentation changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add docs
          git commit -m 'docs: HTML autogenerated after spec update'
          git push
